-- #1: Crie uma tabela chamada "PRODUTO" com as seguintes colunas: 
-- 			ID (serial), 
-- 			CÓDIGO (varchar 3), 
-- 			DESCRIÇÃO (varchar 100), 
-- 			UNIDADEMEDIDA (varchar 2), 
-- 			VALOR (monetario 10,2), 
-- 			CUSTO (monetario 10,2), 
-- 			DATACADASTRO (date), 
-- 			INATIVO (boolean).

CREATE DATABASE AULA04_EXERCICIOS;

CREATE TABLE PRODUTO(
	ID SERIAL,
	CODIGO VARCHAR (3),
	DESCRICAO VARCHAR (100),
	UNIDADEMEDIDA VARCHAR (2),
	VALOR NUMERIC (10,2),
	CUSTO NUMERIC (10,2),
	DATACADASTRO DATE,
	INATIVO BOOLEAN
);


-- #2: Altere a tabela "PRODUTO" para que a coluna ID seja sua chave primaria;
ALTER TABLE PRODUTO
	ADD CONSTRAINT PK_PRODUTO_ID 
	PRIMARY KEY (ID);


-- #3: Insira 10 produtos na tabela "PRODUTO" conforme a imagem fornecida:
INSERT INTO PRODUTO 
	(CODIGO,DESCRICAO,UNIDADEMEDIDA,VALOR,CUSTO,DATACADASTRO,INATIVO)
VALUES
	('P01','Refrigerante 2L','UN',5.99, 4.00,'2022-01-10',FALSE),
	('P02','Alface','KG',0.99, 0.70,'2022-01-10',FALSE),
	('P03','Arroz 5KG','UN',19.99,18.59,'2022-01-10',FALSE),
	('P04','Feijao 1KG','UN',5.99,4.99,'2022-01-10',FALSE),
	('P05','Cerveja 600ML','UN',2.99,2.49,'2022-02-12',FALSE),
	('P06','Amendoim 500G','UN',2.50,2.00,'2022-02-12',FALSE),
	('P07','Pipoca 200G','UN',4.00,3.00,'2022-02-12',FALSE),
	('P08','Pacote Bala 1KG','UN',7.89,6.50,'2021-12-24',FALSE),
	('P09','Uva','KG',4.50,3.00,'2021-12-24',FALSE),
	('P10','Abacaxi','KG',1.99,1.50,'2021-12-24',FALSE);	
	

-- #4: Inclua na tabela "PRODUTO" a coluna TIPO (varchar);	
ALTER TABLE PRODUTO ADD COLUMN TIPO VARCHAR(30);



-- #5: Atualize os tipos de produtos, conforme exemplo: (Geladeira, Farinaceos, Feira, Doces);
	UPDATE PRODUTO SET TIPO = 'Farinaceos' WHERE ID =3;
	UPDATE PRODUTO SET TIPO = 'Farinaceos' WHERE ID =4;
	UPDATE PRODUTO SET TIPO = 'Farinaceos' WHERE ID =6;
	UPDATE PRODUTO SET TIPO = 'Farinaceos' WHERE ID =7;
	
	UPDATE PRODUTO SET TIPO = 'Geladeira' WHERE ID = 1 OR ID = 5;
	
	UPDATE PRODUTO SET TIPO = 'Feira' WHERE ID IN(9,10,2);
	
	UPDATE PRODUTO SET TIPO = 'Doces' WHERE CODIGO = 'P08';



-- #9: Altere a Tabela "PRODUTO" insira a coluna QTDESTOQUE(Float);
ALTER TABLE PRODUTO 
	ADD COLUMN QTDESTOQUE FLOAT;	

-- #10: Insira valores de estoque na tabela "PRODUTO";
-- 	#10.1 - Liste todos os produtos da tabela PRODUTO	
UPDATE PRODUTO SET qtdestoque = 800 WHERE ID = 1;
UPDATE PRODUTO SET qtdestoque = 2000 WHERE ID = 3;
UPDATE PRODUTO SET qtdestoque = 100 WHERE ID = 4;
UPDATE PRODUTO SET qtdestoque = 900 WHERE ID = 5;
UPDATE PRODUTO SET qtdestoque = 50 WHERE ID = 6;
UPDATE PRODUTO SET qtdestoque = 80 WHERE ID = 7;
UPDATE PRODUTO SET qtdestoque = 10 WHERE ID = 8;
UPDATE PRODUTO SET qtdestoque = 250.500 WHERE TIPO = 'Feira';


SELECT * FROM PRODUTO; 

-- #11: Utilizando SELECT, selecione todas informações da tabela PRODUTO onde que possuem VALOR superior a R$ 4,00
SELECT * FROM PRODUTO WHERE VALOR > 4;


-- #12: Liste apenas a DESCRIÇÃO,CODIGO,UNIDADE DE MEDIDA e VALOR dos PRODUTOS com unidade de medida = UN 
SELECT DESCRICAO,CODIGO,UNIDADEMEDIDA,VALOR 
	FROM PRODUTO 
	WHERE UNIDADEMEDIDA = 'UN';

-- #13: Liste apenas os PRODUTOS 
-- 			cadastrados a partir do começo de 2022, 
-- 			com CUSTO menor que R$ 4,00 
-- 			e VALOR menor que R$ 10,00
SELECT 
	CODIGO,
	DESCRICAO,
	CAST(VALOR AS MONEY),
	CUSTO::MONEY,
	DATACADASTRO,
	TIPO
FROM PRODUTO
	WHERE DATACADASTRO >= '2022-01-01' 
		AND CUSTO < 4.00 
		AND VALOR < 10.0
	

	
-- #6: Crie uma tabela "CLIENTE" com as seguintes colunas: 
-- 		NOME (varchar 150), 
-- 		CODIGO (varchar 3), 
-- 		CPF (varchar 11), 
-- 		TELEFONE (varchar 11), 
-- 		DATACADASTRO (date), 
-- 		OBSERVACOES (varchar 18), 
-- 		INATIVO (boolean);
		
		
CREATE TABLE CLIENTE (
    NOME VARCHAR(150),
    CODIGO VARCHAR (3),
    CPF VARCHAR (11),
    TELEFONE VARCHAR(11),
    DATACADASTRO DATE,
    OBSERVACOES VARCHAR(30),
    INATIVO BOOLEAN
);	
	
	
ALTER TABLE CLIENTE 
	ADD CONSTRAINT UK_CLIENTE_CPF 
	UNIQUE (CPF);
	
ALTER TABLE CLIENTE 
	ADD CONSTRAINT UK_CLIENTE_CODIGO 
	UNIQUE (CODIGO);
	
-- #7: Insira 6 clientes na tabela, conforme relação da imagem;
INSERT INTO CLIENTE 
	(NOME, CODIGO, CPF, TELEFONE, DATACADASTRO, OBSERVACOES, INATIVO) 
VALUES 
    ('Maria Silva', 'C01', '12345678910', '43 34721122', '2021-12-01', 'Cliente Bom', FALSE),
    ('João Santos', 'C02', '98765432100', '43 34723020', '2021-12-01', 'Cliente Bom', FALSE),
    ('Ana Costa', 'C03', '45678912345', '43 34721152', '2022-01-14', 'Cliente Inadimplente', FALSE),
    ('Pedro Souza', 'C04', '32165498711', '43 34721011', '2022-01-14', 'Cliente Regular', FALSE),
    ('Lucas Ferreira', 'C05', '74185296300', '43 34728085', '2022-01-14', 'Cliente Regular', FALSE),
    ('Julia Oliveira', 'C06', '36925814722', '43 34722310', '2021-06-06', 'Cliente Excelente', FALSE);



-- #8: Adicione uma coluna nova na tabela cliente com nome = ID do tipo serial, e torne ela a CHAVE PRIMARIA da tabela	
ALTER TABLE CLIENTE 
	ADD COLUMN ID SERIAL NOT NULL;
	
ALTER TABLE CLIENTE 
	ADD CONSTRAINT PK_CLIENTE_ID 
	PRIMARY KEY(ID);
	
-- 8.1 - Liste todos os CLIENTES com SELECT	
SELECT * FROM CLIENTE;


-- #12: Utilizando SELECT, selecione somente os CLIENTES com situação de cadastro (OBSERVACOES) = 'Cliente Bom'
SELECT * FROM CLIENTE WHERE OBSERVACOES = 'Cliente Bom';




--# ATIVIDADES GABRIEL ARAUJO FERNANDES


--#01
	SELECT CODIGO,DESCRICAO,UNIDADEMEDIDA,QTDESTOQUE FROM PRODUTO WHERE QTDESTOQUE > 200 AND UNIDADEMEDIDA = 'UN';

--#02
	SELECT * FROM PRODUTO WHERE TIPO = 'Farinaceos'; 

--#03
    SELECT * FROM PRODUTO WHERE TIPO = 'Farinaceos' OR TIPO = 'Feira';

--#04 
	
	SELECT CODIGO, DESCRICAO, UNIDADEMEDIDA, VALOR, CUSTO, (VALOR - CUSTO) AS LUCRO FROM PRODUTO WHERE TIPO = 'Geladeira' AND (VALOR - CUSTO) >= 1.00;
	
	
--#05 
	SELECT CODIGO, DESCRICAO, UNIDADEMEDIDA,VALOR, CUSTO,(VALOR - CUSTO) AS LUCRO FROM PRODUTO WHERE TIPO = 'Feira';

--#06
	ALTER TABLE PRODUTO ADD COLUMN IMPOSTO NUMERIC 
		UPDATE PRODUTO SET IMPOSTO = 0.50 WHERE TIPO = 'Geladeira'
		UPDATE PRODUTO SET IMPOSTO = 0 WHERE TIPO = 'Feira'
		UPDATE PRODUTO SET IMPOSTO = 0.99 WHERE TIPO = 'Farinaceos'
		UPDATE PRODUTO SET IMPOSTO = 0.39 WHERE TIPO = 'Doces'

		SELECT DESCRICAO,TIPO,IMPOSTO FROM PRODUTO
		SELECT * FROM PRODUTO
--#07
	SELECT CODIGO,DESCRICAO,VALOR::NUMERIC::MONEY, CUSTO::NUMERIC::MONEY, IMPOSTO::NUMERIC::MONEY,(IMPOSTO + CUSTO ) AS CUSTO_REAL FROM PRODUTO;

--#08
	SELECT CODIGO,DESCRICAO,VALOR::NUMERIC::MONEY, CUSTO::NUMERIC::MONEY, IMPOSTO::NUMERIC::MONEY, VALOR - (IMPOSTO + CUSTO) AS LUCRO_REAL FROM PRODUTO;
	
	SELECT CODIGO,DESCRICAO,VALOR::NUMERIC::MONEY, CUSTO::NUMERIC::MONEY, IMPOSTO::NUMERIC::MONEY, VALOR - (IMPOSTO + CUSTO) AS LUCRO_REAL, 
		VALOR - (IMPOSTO + CUSTO) > 0 AS LUCRO,  
		VALOR - (IMPOSTO + CUSTO) < 0 AS PREJUIZO FROM PRODUTO;
			
--#09 

--#SELECT *, TO_CHAR (DATACADASTRO, 'DD/MM/YYYY') AS DATACASTRO FROM PRODUTO;
	SELECT  ID, CODIGO, DESCRICAO, UNIDADEMEDIDA, VALOR, CUSTO, INATIVO, TIPO, QTDESTOQUE, IMPOSTO, TO_CHAR (DATACADASTRO, 'DD/MM/YYYY') AS DATACADASTRO FROM PRODUTO;


--#10
	INSERT INTO PRODUTO VALUES

	(default,'P11', 'Caixa de Bombom 500g', 'UN', 12.99, 10.00,CURRENT_DATE,FALSE,'Doces',1000,1.50),

	(default,'P12', 'Barra de Chocolate 1KG', 'UN', 23.99, 15.00, CURRENT_DATE,FALSE,'Doces',1400,2.89),

	(default,'P13', 'Granulado 1KG', 'UN', 15.99, 10.00, CURRENT_DATE,FALSE,'Doces',200,2.00),

	(default,'P14', 'Barra de Chocolate 200g', 'UN', 4.99, 1.99, CURRENT_DATE,FALSE,'Doces',4000,1.29);

	SELECT * FROM PRODUTO
--#11

	SELECT * FROM PRODUTO WHERE DATACADASTRO >'2023/01/01'
	SELECT CODIGO, DESCRICAO,TO_CHAR (DATACADASTRO, 'DD/MM/YYYY') AS DATACADASTRO FROM PRODUTO;

	SELECT * FROM PRODUTO



